;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	indent-for-tab-command
	ruby-electric-space
	sgml-close-tag
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	autopair-skip-close-maybe
	jedi:dot-complete
	))
