#!/bin/bash
set -e

echo "==================="
echo "Running Brew Bundle"
brew bundle
echo "Brew Bundle Done"
echo "==================="

echo ""

echo "==================="
echo "Running stow bash"
stow bash
echo "Stow stash Done"
echo "==================="

echo ""

echo "==================="
echo "Running stow ssh"
if [ $(uname) == "Darwin" ]; then
    cp ssh/.ssh/mac_config ssh/.ssh/config
else
    cp ssh/.ssh/linux_config ssh/.ssh/config
fi
stow ssh
echo "Stow ssh Done"
echo "==================="

echo ""

echo "==================="
echo "Running stow tmux"
stow tmux
echo "Stow tmux Done"
echo "==================="

echo ""

echo "==================="
echo "Running stow emacs"
stow emacs
echo "Stow emacs Done"
echo "==================="

echo ""

echo "==================="
echo "Running stow pylint"
stow pylint
echo "Stow pylint Done"
echo "==================="

echo ""

echo "==================="
echo "Running stow git"
cp git/.gitconfig.tmpl git/.gitconfig
stow git
if [ $(hostname) == "nayefmacbook" ] || [ $(uname) != "Darwin" ]; then
    git config --global user.email "nayef@hudson-trading.com"
else
    git config --global user.email "nrcopty@gmail.com"
fi
echo "Stow git Done"
echo "==================="
