#!/usr/bin/env ruby
# Usage: boostrap [optional arg stow package]

require 'erb'
require 'ostruct'
require 'fileutils'

$supported_packages = [:bash, :tmux, :git, :emacs, :ssh]
$platform = RUBY_PLATFORM
$linux = 'linux'
$osx = 'darwin'

def stow(package)
  unless $supported_packages.include? package
    puts "No package called #{package}"
    return
  end

  if package == :git
    erb = ERB.new(File.read('git/.gitconfig.erb'))
    email = ($platform.include? $osx) ? 'nrcopty@gmail.com' : 'ncopty@appnexus.com'
    namespace = OpenStruct.new(:git_email => email)
    result = erb.result(namespace.instance_eval { binding })
    File.write('git/.gitconfig', result)
  end

  if package == :ssh and $platform.include? $osx
    return
  end

  if package == :bash
    if File.exist?('../.bash_profile')
      FileUtils.mv('../.bash_profile', '../.bash_profile.bak')
    end
    if File.exist?('../.bashrc')
      FileUtils.mv('../.bashrc', '../.bashrc.bak')
    end
  end

  unless system("stow #{package.to_s}")
    puts "There was an error stowing #{package}."
  end
end

def stow_packages(packages)
  if packages.empty?
    $supported_packages.each do |pkg|
      puts "Stowing #{pkg}"
      stow pkg.to_sym
    end
  else
    packages.each do |pkg|
      puts "Stowing #{pkg}"
      stow pkg.to_sym
    end
  end
end

if __FILE__ == $0
  stow_packages ARGV
end
