tap 'Homebrew/bundle'
tap 'caskroom/cask'
brew 'python'
brew 'python3'
brew 'hr'
brew 'stow'
brew 'git'
brew 'youtube-dl'
brew 'ffmpeg'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'emacs', args: ['cocoa']
brew 'fpp'
brew 'mycli'
brew 'diff-so-fancy'
brew 'tree'
brew 'the_silver_searcher'
brew 'jq'
brew 'httpie'
brew 'fasd'
brew 'rtags'
brew 'icdiff'
brew 'bash-completion'
brew 'trash'

tap 'simeji/jid'
brew 'jid'

# C/C++
brew 'glib'
brew 'cmake'
brew 'llvm', args: ['with-clang']
brew 'gdb'
brew 'rtags'

# Cask - GUI
cask 'emacs'
cask 'google-chrome'
cask 'iterm2'
cask 'stay'
cask 'messenger'
cask 'whatsapp'
cask 'alfred'
cask 'haskell-platform'
