tap 'Homebrew/bundle'
tap 'caskroom/cask'
brew 'brew-cask'
brew 'cask'
brew 'hr'
brew 'git'
brew 'hub'
brew 'youtube-dl'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'emacs', args: ['cocoa']
brew 'fpp'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-default-packages'
brew 'mycli'
brew 'diff-so-fancy'
brew 'autojump'

cask 'emacs'
