tap 'Homebrew/bundle'
tap 'caskroom/cask'
tap 'simeji/jid'
tap 'homebrew/services'
tap 'caskroom/fonts'

brew 'python'
brew 'python3'
brew 'hr'
brew 'stow'
brew 'git'
brew 'youtube-dl'
brew 'ffmpeg'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'emacs', args: ['cocoa']
brew 'fpp'
brew 'mycli'
brew 'diff-so-fancy'
brew 'tree'
brew 'the_silver_searcher'
brew 'jq'
brew 'httpie'
brew 'fasd'
brew 'icdiff'
brew 'bash-completion'
brew 'trash'
brew 'jid'
brew 'wget'
brew 'fd'
brew 'bench'
brew 'coreutils'
brew 'fzf'
brew 'watchman'

# C/C++
brew 'glib'
brew 'cmake'
brew 'llvm', args: ['with-clang']
brew 'gdb'
brew "rtags", restart_service: true

# Cask - GUI
# cask 'emacs'
# cask 'iterm2'
# cask 'alfred'
cask 'font-iosevka'
# cask 'haskell-platform'
