language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
script: nosetests test --verbose
notifications:
  email:
    - filippo.valsorda@gmail.com
    - phihag@phihag.de
    - jaime.marquinez.ferrandiz+travis@gmail.com
    - yasoob.khld@gmail.com
#  irc:
#    channels:
#      - "irc.freenode.org#youtube-dl"
#    skip_join: true
