# https://github.com/Homebrew/homebrew-brewdler

tap 'caskroom/cask'
brew 'brew-cask'
brew 'cask'
brew 'hr'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'youtube-dl'
brew 'tmux'
brew 'emacs', args: ['cocoa']
>84;0;0cbrew 'fpp'
tap 'jawshooah/pyenv'
brew 'pyenv-default-packages'
brew 'mycli'
brew 'diff-so-fancy'

cask 'macdown'
cask 'emacs'
